version: 2

builds:
  - id: bitflip
    main: ./cmd/bitflip
    binary: bitflip
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/baidu/nettools/version.Version={{.Version}} -X github.com/baidu/nettools/version.Commit={{.Commit}} -X github.com/baidu/nettools/version.Date={{.Date}}

  - id: bitflip6
    main: ./cmd/bitflip6
    binary: bitflip6
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/baidu/nettools/version.Version={{.Version}} -X github.com/baidu/nettools/version.Commit={{.Commit}} -X github.com/baidu/nettools/version.Date={{.Date}}

  - id: baize
    main: ./cmd/baize
    binary: baize
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/baidu/nettools/version.Version={{.Version}} -X github.com/baidu/nettools/version.Commit={{.Commit}} -X github.com/baidu/nettools/version.Date={{.Date}}

  - id: lidar
    main: ./cmd/lidar
    binary: lidar
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/baidu/nettools/version.Version={{.Version}} -X github.com/baidu/nettools/version.Commit={{.Commit}} -X github.com/baidu/nettools/version.Date={{.Date}}

  - id: mping
    main: ./cmd/mping
    binary: mping
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/baidu/nettools/version.Version={{.Version}} -X github.com/baidu/nettools/version.Commit={{.Commit}} -X github.com/baidu/nettools/version.Date={{.Date}}

  - id: mping6
    main: ./cmd/mping6
    binary: mping6
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/baidu/nettools/version.Version={{.Version}} -X github.com/baidu/nettools/version.Commit={{.Commit}} -X github.com/baidu/nettools/version.Date={{.Date}}

archives:
  - id: default
    ids:
      - bitflip
      - bitflip6
      - baize
      - lidar
      - mping
      - mping6
    formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
